### ISSUE TITLE
JVM实战篇大部分图片无法正常显示

### ISSUE THREAD

**Issue by zjl369** [iceliyr/note-jvm#1]
从 [note-jvm/7.2、JVM实战篇.md at master · iceliyr/note-jvm](https://github.com/iceliyr/note-jvm/blob/master/7.2%E3%80%81JVM%E5%AE%9E%E6%88%98%E7%AF%87.md#%E9%98%BF%E9%87%8C%E4%BA%91%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA%E4%BA%86%E8%A7%A3%E5%8D%B3%E5%8F%AF) 这里开始，基本上所有图片都不能正常显示了，前面也有不能显示的。

**Comment by iceliyr** [comment]
你下载在本地之后就可以看了

**Comment by zjl369** [comment]
呃，不是。那些不能看的图片链接是这样的 <https://lisxpq12rl7.feishu.cn/space/api/box/stream/download/asynccode/?code=Mzg5M2VmYmM0OWI2NjQ1OWM5NDFlMzM2OTEzNTZhNDFfVjBnaFJFUl......>应该是种防盗链机制，过一段时间就不能访问了。你这篇笔记里有255张图片没下载到本地……

后来我去飞书上直接粘的笔记，把图片批量下载下来了
